USE BD_BOTICA;

SELECT * FROM V1Z_LABORATORIO;

INSERT INTO V1Z_LABORATORIO (LabCod, LabDes, LabEstReg)
VALUES
	(1, "Andromaco", 'A'),
    (2, "Andromeda", 'A'),
    (3, "Gamma", 'A');

DELETE FROM V1Z_LABORATORIO WHERE LabCod>0;

SELECT V1M_ARTICULO.ArtCod, V1M_ARTICULO.ArtNom,
V1Z_LABORATORIO.LabDes AS ArtLab,
V1Z_CATEGORIA.CatDes AS ArtCat,
V1Z_TIPO_UNIDAD_MEDIDA.TipUniMedDes AS ArtTipUniMed,
V1M_ARTICULO.ArtFecVenAño, V1M_ARTICULO.ArtFecVenMes, V1M_ARTICULO.ArtFecVenDia,
V1M_ARTICULO.ArtPreUni, V1M_ARTICULO.ArtSto, V1M_ARTICULO.ArtEstReg
FROM V1M_ARTICULO
JOIN V1Z_CATEGORIA ON V1M_ARTICULO.ArtCat=V1Z_CATEGORIA.CatCod
JOIN V1Z_LABORATORIO ON V1M_ARTICULO.ArtLab=V1Z_LABORATORIO.LabCod
JOIN V1Z_TIPO_UNIDAD_MEDIDA ON V1M_ARTICULO.ArtTipUniMed=V1Z_TIPO_UNIDAD_MEDIDA.TipUniMedCod;

UPDATE V1M_ARTICULO
SET ArtPreUni=20.28,
ArtSto=30,
ArtCat=3
WHERE ArtCod=4;

SELECT * FROM V1M_ARTICULO;

# READ ALL
SELECT ArtCod, ArtNom,
LabDes AS ArtLab,
CatDes AS ArtCat,
TipUniMedDes AS ArtTipUniMed,
ArtFecVenAño, ArtFecVenMes, ArtFecVenDia,
ArtPreUni, ArtSto, ArtEstReg
FROM V1M_ARTICULO
JOIN V1Z_LABORATORIO ON ArtLab=LabCod
JOIN V1Z_CATEGORIA ON ArtCat=CatCod
JOIN V1Z_TIPO_UNIDAD_MEDIDA ON ArtTipUniMed=TipUniMedCod
ORDER BY ArtCod DESC;

# READ ONE
SELECT ArtCod, ArtNom,
LabDes AS ArtLab,
CatDes AS ArtCat,
TipUniMedDes AS ArtTipUniMed,
ArtFecVenAño, ArtFecVenMes, ArtFecVenDia,
ArtPreUni, ArtSto, ArtEstReg
FROM V1M_ARTICULO
JOIN V1Z_LABORATORIO ON ArtLab=LabCod
JOIN V1Z_CATEGORIA ON ArtCat=CatCod
JOIN V1Z_TIPO_UNIDAD_MEDIDA ON ArtTipUniMed=TipUniMedCod
WHERE ArtCod=1;

SELECT * FROM V1M_ARTICULO;
DELETE FROM V1M_ARTICULO WHERE ArtCod BETWEEN 5 AND 6;

SELECT * FROM GZZ_ROL;
INSERT INTO GZZ_ROL (RolDes) VALUES
	("ADMIN"), ("STOREKEEPER"), ("REGULAR");
SELECT * FROM GZM_USUARIO;
INSERT INTO GZM_USUARIO (
	UsuNom, UsuApe,
    RolCod,
    UsuEma, UsuTel, UsuDir,
    UsuFecInsAño, UsuFecInsMes, UsuFecInsDia,
    UsuEstReg
) VALUES (
	"SOME NAME", "SOME SURNAME",
    1,
    "some@email.com", "999999999", "SOME ADDRESS",
    2023, 7, 8,
    "A"
);

# READ ALL USERS
SELECT
UsuCod, UsuNom, UsuApe,
RolDes AS UsuRol,
UsuEma, UsuTel, UsuDir,
UsuFecInsAño, UsuFecInsMes, UsuFecInsDia,
UsuEstReg
FROM GZM_USUARIO
JOIN GZZ_ROL ON GZM_USUARIO.RolCod=GZZ_ROL.RolCod
ORDER BY UsuCod DESC;

# READ ONE USER
SELECT
UsuCod, UsuNom, UsuApe,
RolDes AS UsuRol,
UsuEma, UsuTel, UsuDir,
UsuFecInsAño, UsuFecInsMes, UsuFecInsDia,
UsuEstReg
FROM GZM_USUARIO
JOIN GZZ_ROL ON GZM_USUARIO.RolCod=GZZ_ROL.RolCod
WHERE UsuCod=2;

SELECT * FROM V1Z_TIPO_ESTADO_PEDIDO;
INSERT INTO V1Z_TIPO_ESTADO_PEDIDO (TipEstPedDes)
VALUES ("EN PROCESO"), ("COMPLETADO");

# PEDIDOS
SELECT * FROM V1T_PEDIDO;
INSERT INTO V1T_PEDIDO (
	PedCli,
	PedFecAño, PedFecMes, PedFecDia,
    TipEstPedCod,
	PedEstReg
) VALUES (
	2,
	2023, 7, 11,
    1,
    "A"
);

SELECT * FROM V1T_PEDIDO;
SELECT * FROM GZM_USUARIO;
# READ ALL PEDIDOS
SELECT
PedNum,

UsuCod AS PedCliCod,
UsuNom AS PedCliNom,
UsuApe AS PedCliApe,
UsuEma AS PedCliEma,
UsuTel AS PedCliUsuTel,
UsuDir AS PedCliUsuDir,
UsuEstReg AS PedCliEstReg,

PedFecAño, PedFecMes, PedFecDia,
TipEstPedDes AS PedTipEstPed,
PedEstReg
FROM V1T_PEDIDO
JOIN GZM_USUARIO ON PedCli=UsuCod
JOIN V1Z_TIPO_ESTADO_PEDIDO ON V1T_PEDIDO.TipEstPedCod=V1Z_TIPO_ESTADO_PEDIDO.TipEstPedCod
ORDER BY PedNum DESC;

SELECT * FROM V1T_PEDIDO;
SELECT * FROM V1M_ARTICULO;
SELECT * FROM V1T_PEDIDO_ARTICULO;

# ADD ARTICULO TO PEDIDO
INSERT INTO V1T_PEDIDO_ARTICULO (
PedArtPed, PedArtArt,
PedArtPreUni,
PedArtCanSol, PedArtCanDes,
PedArtEstReg
) VALUES (
1, 4,
25.75,
40, 20,
"A"
);

SELECT * FROM V1T_PEDIDO_ARTICULO;

# READ ALL ARTICULOS FROM A PEDIDO
SELECT PedArtPed,
ArtCod AS PedArtArtCod,
ArtNom AS PedArtArtNom,
PedArtPreUni,
PedArtCanSol,
PedArtCanDes,
PedArtEstReg
FROM V1T_PEDIDO_ARTICULO
JOIN V1M_ARTICULO ON PedArtArt=ArtCod
WHERE PedArtPed=1;
