USE BD_BOTICA;

SELECT * FROM V1Z_LABORATORIO;

INSERT INTO V1Z_LABORATORIO (LabCod, LabDes, LabEstReg)
VALUES
	(1, "Andromaco", 'A'),
    (2, "Andromeda", 'A'),
    (3, "Gamma", 'A');

DELETE FROM V1Z_LABORATORIO WHERE LabCod>0;

SELECT V1M_ARTICULO.ArtCod, V1M_ARTICULO.ArtNom, 
V1Z_LABORATORIO.LabDes AS ArtLab, 
V1Z_CATEGORIA.CatDes AS ArtCat, 
V1Z_TIPO_UNIDAD_MEDIDA.TipUniMedDes AS ArtTipUniMed,
V1M_ARTICULO.ArtFecVenAño, V1M_ARTICULO.ArtFecVenMes, V1M_ARTICULO.ArtFecVenDia,
V1M_ARTICULO.ArtPreUni, V1M_ARTICULO.ArtSto, V1M_ARTICULO.ArtEstReg
FROM V1M_ARTICULO
JOIN V1Z_CATEGORIA ON V1M_ARTICULO.ArtCat=V1Z_CATEGORIA.CatCod
JOIN V1Z_LABORATORIO ON V1M_ARTICULO.ArtLab=V1Z_LABORATORIO.LabCod
JOIN V1Z_TIPO_UNIDAD_MEDIDA ON V1M_ARTICULO.ArtTipUniMed=V1Z_TIPO_UNIDAD_MEDIDA.TipUniMedCod;

UPDATE V1M_ARTICULO
SET ArtPreUni=20.28,
ArtSto=30,
ArtCat=3
WHERE ArtCod=4;

SELECT * FROM V1M_ARTICULO;

# READ ALL
SELECT ArtCod, ArtNom,
LabDes AS ArtLab,
CatDes AS ArtCat,
TipUniMedDes AS ArtTipUniMed,
ArtFecVenAño, ArtFecVenMes, ArtFecVenDia,
ArtPreUni, ArtSto, ArtEstReg
FROM V1M_ARTICULO
JOIN V1Z_LABORATORIO ON ArtLab=LabCod
JOIN V1Z_CATEGORIA ON ArtCat=CatCod
JOIN V1Z_TIPO_UNIDAD_MEDIDA ON ArtTipUniMed=TipUniMedCod
ORDER BY ArtCod DESC;

# READ ONE
SELECT ArtCod, ArtNom,
LabDes AS ArtLab,
CatDes AS ArtCat,
TipUniMedDes AS ArtTipUniMed,
ArtFecVenAño, ArtFecVenMes, ArtFecVenDia,
ArtPreUni, ArtSto, ArtEstReg
FROM V1M_ARTICULO
JOIN V1Z_LABORATORIO ON ArtLab=LabCod
JOIN V1Z_CATEGORIA ON ArtCat=CatCod
JOIN V1Z_TIPO_UNIDAD_MEDIDA ON ArtTipUniMed=TipUniMedCod
WHERE ArtCod=1;

SELECT * FROM V1M_ARTICULO;
DELETE FROM V1M_ARTICULO WHERE ArtCod BETWEEN 5 AND 6;

SELECT * FROM GZZ_ROL;
INSERT INTO GZZ_ROL (RolDes) VALUES 
	("ADMIN"), ("STOREKEEPER"), ("REGULAR");
SELECT * FROM GZM_USUARIO;
INSERT INTO GZM_USUARIO (
	UsuNom, UsuApe,
    RolCod,
    UsuEma, UsuTel, UsuDir, 
    UsuFecInsAño, UsuFecInsMes, UsuFecInsDia,
    UsuEstReg
) VALUES (
	"SOME NAME", "SOME SURNAME",
    1,
    "some@email.com", "999999999", "SOME ADDRESS",
    2023, 7, 8,
    "A"
);

# READ ONE USER
SELECT
UsuCod, UsuNom, UsuApe,
RolDes AS UsuRol,
UsuEma, UsuTel, UsuDir,
UsuFecInsAño, UsuFecInsMes, UsuFecInsDia,
UsuEstReg
FROM GZM_USUARIO
JOIN GZZ_ROL ON GZM_USUARIO.RolCod=GZZ_ROL.RolCod
ORDER BY UsuCod DESC;

SELECT
UsuCod, UsuNom, UsuApe,
RolDes AS UsuRol,
UsuEma, UsuTel, UsuDir,
UsuFecInsAño, UsuFecInsMes, UsuFecInsDia,
UsuEstReg
FROM GZM_USUARIO
JOIN GZZ_ROL ON GZM_USUARIO.RolCod=GZZ_ROL.RolCod
WHERE UsuCod=2;

SELECT * FROM V1T_PEDIDO;